package com.eme22.hospitalwebserver.repository;

import com.eme22.hospitalwebserver.model.Area;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@Repository
public interface AreaRepository extends JpaRepository<Area, Long>, JpaSpecificationExecutor<Area> {
    Optional<Area> findByMedicsById_Dni(@NonNull long dni);



}
