package com.eme22.hospitalwebserver.repository;

import com.eme22.hospitalwebserver.model.Medic;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@Repository
public interface MedicRepository extends JpaRepository<Medic, Long>, JpaSpecificationExecutor<Medic> {
    List<Medic> findBySpecialityBySpecId_Id(long id);

    @Query("SELECT m FROM Medic m WHERE m.id NOT IN (SELECT h.medic.id FROM Holiday h WHERE h.date = ?1)")
    List<Medic> findByHolidays_DateIsNotIn(LocalDate date);

    @Query("SELECT m FROM Medic m WHERE m.id IN (SELECT h.medic.id FROM Holiday h WHERE h.date = ?1)")
    List<Medic> findByHolidays_DateIsIn(LocalDate date);





}
