package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Appointment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.lang.NonNull;

import java.util.List;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "appointment")
public interface AppointmentRepository extends JpaRepository<Appointment, Long>, JpaSpecificationExecutor<Appointment> {
    @Query("select a from Appointment a where a.medicByMedicId.id = ?1")
    List<Appointment> findByMedicByMedicId_Id(long id);

    @Query("select a from Appointment a where a.medicByMedicId.dni = ?1")
    List<Appointment> findByMedicByMedicId_Dni(long dni);

    //List<Appointment> findByMedicByMedicId_Id(@NonNull long id);

    List<Appointment> findByPatientByPatientId_Id(@NonNull long id);

    //List<Appointment> findByMedicByMedicId_Dni(@NonNull long dni);

    List<Appointment> findByPatientByPatientId_Dni(@NonNull long dni);

    List<Appointment> findByPatientByPatientId_DniAndFinished(long dni, boolean finished);



}
