package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Area;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.lang.NonNull;

import java.util.Optional;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "area")
public interface AreaRepository extends JpaRepository<Area, Long>, JpaSpecificationExecutor<Area> {
    Optional<Area> findByMedicsById_Dni(@NonNull long dni);



}
