package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Holiday;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.List;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "holiday")
public interface HolidayRepository extends JpaRepository<Holiday, Long>, JpaSpecificationExecutor<Holiday> {
    @Query("select h from Holiday h where h.medic.id = ?1")
    List<Holiday> findByMedic_Id(long id, Pageable pageable);

}
