package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Medic;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "medic")
public interface MedicRepository extends JpaRepository<Medic, Long>, JpaSpecificationExecutor<Medic> {

}
