package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Medication;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "medication")
public interface MedicationRepository extends JpaRepository<Medication, Long>, JpaSpecificationExecutor<Medication> {

}
