package com.eme22.hospitalwebserver.dao;

import com.eme22.hospitalwebserver.model.Patient;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.lang.NonNull;

import java.util.Optional;

/**
* Generated by Spring Data Generator on 23/05/2023
*/
@RepositoryRestResource(path = "patient")
public interface PatientRepository extends JpaRepository<Patient, Long>, JpaSpecificationExecutor<Patient> {
    Optional<Patient> findByDni(@NonNull long dni);

}
